---
title: "Murrel Pereira"
output: 
  html_document:
    toc: true
    toc_float: true
---

### **Education**
##### Columbia University Mailman School of Publich Health *(2017 - 2020)*

* MS in Biostatistics

##### Carnegie Mellon University *(2008 - 2012)*

* BS in Chemical Engineering
  *Bioprocessing Track*
* BS in Biomedical Engineering


### **Professional Experience**

#### Regeneron Pharmaceuticals *(2013 - Present)*
* Data Manager and Data Scientist 
  + Spotfire Developer
    + Developed dashboards for seed train and production bioreactor visualization and monitoring of NOVA and quality data
  + Spotfire Dashboard Manager
    + Trained and led teams across upstream and downstream process development to develop dashboards based on LIMS data
  + QbD Automation Team
    + Harmonized statistical QbD methods across process development
    + Wrote and reviewed statistical guides for department
    + Conducted vision meetings to understand pain points across department and areas for automation
    + Led team in development of scripts to automate statistical tables in development reports and BLAs
  + OSIsoft PI Administrator
    + Onboarded cell culture lab equipment's online data to PI system
    + Developed batch trigger logic for small scale bioreactors
    + Maintained/developed PI alarms for lab equipment
    + Maintained glucose/antifoam autofeed system for cell culture bioreactors
    + PI AF, BI Integrator, Event Frames, Processbook, PI Vision, PI Datalink
  + Freezer inventory app
    + Product owner to manage inventory of cell culture retains in lab freezers for large experiments
  + Predictive Modeling Database
    + Stakeholder for department-wide project to manage predictive models
  + Risk Management Database Project Manager
    + Onboarding of risk management system across 2 departments within Regeneron
  + Central Data Team
    + Governance team to manage data management requests
    + Work with team to develop strategy for addressing data gaps in department
  + Data Science Team
    + Governance team to collate data science projects throughout department
  + Late Stage Process Machine Learning
    + Develop statistical analyses to identify clusters in late stage upstream processes

* Process Development Engineer
  + Early Stage Process Development
    + Led and supported upstream process development for multiple clinical processes
    + Cell line screening across various life cycle stages of molecule
    + Supported tech transfer for clinical lots at the 2000L manufacturing scale via transmittals, manufacturing record reviews, and troubleshooting of issues
  + Late Stage Process Development
      + Led upstream process development for commercial processes
      + Commercial processes for one bispecific and one monoclonal antibodies
      + Risk assessment of manufacturing processes using QTPP, CQAs, High/Low level unit operation risk assessments, PFMEAS
      + Design and analysis of characterization experiments to identify CPPs in bioreactor processes
      + Supported initial transfer to 2000L manufacturing site via transmittals, manufacturing record reviews, troubleshooting batch issues
      + Supporting validation (PPQ) campaigns at the manufacturing site via transmittals, manufacturing record reviews, troubleshooting batch issues, PPQ report review, PAR report reviews
      + Documentation: ELN, development reports,transmittals, BLA
      + Scale Characterization Project: Modeling of scale independent parameters to identify sources of variability in bioreactor performance across scales

#### Deloitte *(2012 - 2013)*
* Data Analytics Associate

#### Goldman Sachs *(2011)*
* Operations Analyst 

### **Skills**

#### Statistics/Programming Tools
JMP, JSL, R, R Markdown, R Shiny, Python, Ironpython, HTML, CSS, SAS, Git

#### Statistical Methods
Linear Regression, Design of Experiments, Stepwise, Time series analysis, Logistic regression, Functional data analysis, Clustering, Clinical trial design, Monte Carlo Simulation, Process Capability analysis

#### Data Management Platforms
TIBCO Spotfire, OSISoft PI, CORE LIMS, Benchling, iRisk, Jira, Confluence, Bitbucket, OPC Software, IDBS ELN

#### Project Management Skills
Agile, Scrum

#### Process Development
CHO cell culture, Sartorius bioreactors, ambr bioreactors, applikon bioreactors, Quality by Design (QbD), bispecific antibody process development, monoclonal antibody process development, medium and feed development, NOVA Flex1, NOVA Flex2, manufacturing record review, transmittal writing, Biologics License Application (BLA) writing, GMP, PAR/NOR setting, process capability, risk assessments
